apiVersion: apps/v1
kind: Deployment
metadata:
  name: paper-rock-scissors
  labels:
    app: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game
          image: denis256/paper-rock-scissors:eefd7
          ports:
            - containerPort: 6969
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: app-config
            items:
              - key: "application.yaml"
                path: "application.yaml"
