apiVersion: apps/v1
kind: Deployment
metadata:
  name: paper-rock-scissors
  labels:
    app: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game
          image: denis256/paper-rock-scissors:eefd7
          env:
            - name: JAVA_OPTS
              value: "-server"
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "512Mi"
              cpu: "1"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 2
            exec:
              command: ["curl", "--fail", "http://localhost:8080/actuator/health"]
          ports:
            - name: game-port
              containerPort: 6969
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: app-config
            items:
              - key: "application.yaml"
                path: "application.yaml"
