apiVersion: v1
kind: Service
metadata:
  name: game-service
  labels:
    app: game
spec:
  type: NodePort
  ports:
    - port: 6969
      nodePort: 30123
      protocol: TCP
  selector:
    app: game